# There is a pre-installed cygwin: http://help.appveyor.com/discussions/suggestions/427-pre-install-cygwin
# But it's old and misses some stuff anyway
version: 0.0.0.0.1-branch-{branch}-build-{build}
shallow_clone: true
cache:
    - c:\cygwin-setup-cache
environment:
    CYGWIN_NOWINPATH: yes
    matrix:
        - cygwin_url: https://cygwin.com/setup-x86_64.exe
        - cygwin_url: https://cygwin.com/setup-x86.exe
install:
    - ps: Invoke-WebRequest $env:cygwin_url -OutFile c:\cygwin-setup.exe
      # libcrypt-devel is needed only on x86_64 and only for modperl... probably some dependency problem.
    - c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages automake,gcc-g++,make,pkg-config,openssl-devel,libicu-devel,zlib-devel,libcrypt-devel,perl,python3-devel,libsasl2-devel,cygport,cmake,libboost-devel
    - c:\cygwin-root\bin\sh -lc "echo Hi"
    - c:\cygwin-root\bin\sh -lc "uname -a"
    - c:\cygwin-root\bin\sh -lc "cat /proc/cpuinfo"
    - c:\cygwin-root\bin\sh -lc "cat /proc/meminfo"
    - c:\cygwin-root\bin\sh -lc "cygcheck -s -v > $APPVEYOR_BUILD_FOLDER/cygcheck.log 2>&1"
    - ps: Push-AppveyorArtifact cygcheck.log
# stdin is broken at AppVeyor, so we open it explicitly as /dev/null
build_script:
    - c:\cygwin-root\bin\sh -lc "cd $APPVEYOR_BUILD_FOLDER; cygport znc.cygport download"
    - c:\cygwin-root\bin\sh -lc "cd $APPVEYOR_BUILD_FOLDER; cygport znc.cygport all < /dev/null"
    - c:\cygwin-root\bin\sh -lc "cd $APPVEYOR_BUILD_FOLDER; tar cjvf dist.tbz */dist"
    - ps: Push-AppveyorArtifact dist.tbz
